### ISSUE TITLE
invalid  yaml

### ISSUE THREAD

**Issue by tierline1** [itdoginfo/sing-box#2]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'sing-box'

```
services:
  sing-box:
    container_name: "sing-box"
    image: 'itdoginfo/sing-box:v1.9.3'
    ports:
      - '443:443'
    environment:
      PROTOCOL: shadowsocks
      PASS: "xxxxxxxxxxxxxxxxxx"
      SERVER: xxxxx
    restart: always
```
